#!/bin/bash

echo "🔧 Invoking git pre-push hook: run linting ..."
# Make linter only commit files that have been touched since the last commit
changed=$(git diff --cached --name-only --diff-filter=ACMR)
if make all; then
  echo "✅ All linting done, files reformatted and check passed."
  git add $changed
else
  echo "❌ Linting failed. Aborting push."
  exit 1
fi
