name: Setup ubuntu
description: Setup ubuntu

inputs:
  packages:
    description: Space-separated list of additional packages to install
    required: false
    default: 'llvm llvm-runtime'

runs:
  using: composite
  steps:
    - name: Update package repository
      shell: bash
      run: |
        sudo apt-get update
    - name: Install base packages
      shell: bash
      run: |
        sudo apt-get install python3-venv python3-pip make -y
    - name: Install additional packages
      if: ${{ inputs.packages != ''}}
      shell: bash
      run: |
        sudo apt-get install ${{ inputs.packages }} -y
    - name: Setup Python venv
      shell: bash
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install -r requirements.txt
        deactivate
        echo "$(pwd)/venv/bin/" >> "$GITHUB_PATH"
