name: Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    name: Test Python (${{ matrix.python-version}})
    strategy:
      fail-fast: false
      matrix:
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ubuntu
        with:
            python-version: ${{ matrix.python-version}} 
      - name: Run tests
        run: |
          python3 -W error test.py